apiVersion: v1
kind: Secret
metadata:
  name: repo-poc-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository 
stringData:
  type: git 
  url: https://github.com/crfjunior65/POC-ArgoCD_07032026.git
  username: crfjunior65
  password: ${GITHUB_TOKEN}
