apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-namespace

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - postgress-deployment.yaml
  - postgress-service.yaml
  - elasticsearch-deployment.yaml
  - elasticsearch-secrets.yaml
  - kibana-deployment.yaml
  - filebeat-kubernetes.yaml
  - kube-state-metrics.yaml